"""auto-migration

Revision ID: 266aa50a3d1c
Revises: b0ae0ff3d416
Create Date: 2025-07-15 21:10:43.451844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266aa50a3d1c'
down_revision: Union[str, Sequence[str], None] = 'b0ae0ff3d416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
