"""auto-migration

Revision ID: b0ae0ff3d416
Revises: 50ae82ae8110
Create Date: 2025-07-15 20:10:49.443871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ae0ff3d416'
down_revision: Union[str, Sequence[str], None] = '50ae82ae8110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'acquirer_brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('report', 'target_brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'target_brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('report', 'acquirer_brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
